#!/bin/sh
DOCKER_IMAGE='azuresdk/azure-cli-python'
DOCKER_TAG='latest'

if [ -t 1 ]; then 
    TERM_OPTION="-ti"
else
    TERM_OPTION="-i"
fi 

docker run $TERM_OPTION --rm -v ${AZURE_CONFIG}:/root/.azure ${DOCKER_IMAGE}:${DOCKER_TAG} az $@