#!/bin/bash
#
# multi-tool - Run the multi-tool container with appropriate volume mounts
#
# Usage: gantry [-c workdir] [-d] [tool tool_args]
#
#   -c : run gantry from within another docker container and use its volume mounts using
#        the workdir argument as the working directory for the gantry container
#   -d : debug mode. Drop into the container using bash as an interactive entry point
#   -m : use the minikube docker enviroment to simplify local work
#

DOCKER_IMAGE="multi-tool"

# Update this if you're using a private docker registry
REGISTRY="quay.io/leopoldodonnell/"

VOLUMES="-v $HOME/.aws:/root/.aws \
        -v ${PWD}:/share \
        -v $HOME/.kube:/root/.kube \
        -v $HOME/.minikube:$HOME/.minikube \
        -v $HOME/.helm:/root/.helm \
        -v /var/run/docker.sock:/var/run/docker.sock"

opt_count=0

while getopts "dmc:" opt ; do
  case "${opt}" in
    c)
      opt_count=$((opt_count + 2))
      MY_CONTAINER_ID=`cat /proc/self/cgroup |awk -F '/' '$2 = "docker" && NR == 1 {print $NF }'`
      VOLUMES="--volumes-from ${MY_CONTAINER_ID} -w ${OPTARG}"
      ;;
    d)
      opt_count=$((opt_count + 1))
      DEBUG="-ti --entrypoint /bin/bash"
      ;;
    m)
      opt_count=$((opt_count + 1))
      eval $(minikube docker-env)
      read -r -d '' MINIKUBE_ENV <<EOF
        -e DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY
        -e DOCKER_HOST=$DOCKER_HOST
        -e DOCKER_CERT_PATH=$DOCKER_CERT_PATH
        -e DOCKER_API_VERSION=$DOCKER_API_VERSION
EOF
      ;;
    *)
      ;;
  esac
done

# get rid of options passed the to script and not passed onto the container
shift $opt_count

docker run --rm \
  ${VOLUMES} \
  ${MINIKUBE_ENV} \
  ${DEBUG} \
  ${REGISTRY}${DOCKER_IMAGE} $@
