# Main Rakefile for multi-tool

mt_libdir = '/mt/lib'
local_libdir = File.dirname(__FILE__) + '/lib'
$LOAD_PATH.unshift(mt_libdir) if Dir.exists? mt_libdir
$LOAD_PATH.unshift(File.expand_path(local_libdir)) if Dir.exists? local_libdir

require 'logger'
require 'multi_tool/command'

LOGGER = Logger.new(STDOUT)
LOGGER.level = Logger::WARN

# Load all default and user supplied Rakefiles
Dir['/mt/tasks/**/*.rb'].each { |rakefile| load(rakefile) }
Dir['tasks/**/*.rb'].each { |rakefile| load(rakefile) } if Dir.exists? "tasks"

task :default => [ :help ]
